"""Transparent, multi-factor risk prioritisation.

This is an explainable scoring model, not a trained machine-learning model.
Every score includes its inputs and an evidence-confidence indicator.
"""

from __future__ import annotations

from typing import Any


CRITICALITY_SCORE = {"Critical": 100.0, "High": 75.0, "Medium": 50.0, "Low": 25.0}
EXPOSED_SERVICES = {"microsoft-ds", "rdp", "telnet", "ftp", "http", "https", "ssh", "msrpc"}


def _risk_level(score: float) -> str:
    if score >= 80:
        return "Critical"
    if score >= 60:
        return "High"
    if score >= 35:
        return "Medium"
    return "Low"


def _confidence(finding: dict[str, Any]) -> float:
    return 95.0 if finding.get("confidence") == "Confirmed" else 60.0


def calculate_ai_risk(vulnerabilities: list[dict[str, Any]], assets: list[dict[str, Any]]) -> dict[str, Any]:
    """Score findings with CVSS, exploit likelihood, asset value and evidence."""
    if not vulnerabilities:
        return {
            "risk_score": 0.0,
            "risk_level": "Low",
            "explanation": "No evidence-supported findings were generated by this assessment.",
            "zero_trust_readiness_score": None,
            "ransomware_risk_index": None,
            "cis_controls_coverage": None,
            "attack_paths": [],
            "analysis": {
                "vulnerability_count": 0,
                "business_criticality": "Low",
                "exploit_analysis": "No CVE-specific exploit intelligence available",
                "network_exposure": False,
                "internet_exposure_assessed": False,
                "epss_threat_index": 0.0,
                "confidence_score": 0.0,
                "model": "Explainable weighted risk model",
            },
        }

    criticality_by_ip = {asset.get("ip"): asset.get("criticality", "Low") for asset in assets}
    per_finding_scores: list[float] = []
    confidence_values: list[float] = []
    max_epss = 0.0
    attack_paths: list[dict[str, Any]] = []

    for finding in vulnerabilities:
        cvss = float(finding.get("cvss", 0.0))
        epss = max(0.0, min(1.0, float(finding.get("epss_score", 0.0))))
        criticality = criticality_by_ip.get(finding.get("ip"), "Low")
        service = finding.get("service", "")
        confidence = _confidence(finding)
        exposure_score = 100.0 if service in EXPOSED_SERVICES else 40.0
        score = (
            cvss * 10 * 0.35
            + epss * 100 * 0.20
            + CRITICALITY_SCORE.get(criticality, 25.0) * 0.25
            + exposure_score * 0.15
            + confidence * 0.05
        )
        per_finding_scores.append(min(100.0, score))
        confidence_values.append(confidence)
        max_epss = max(max_epss, epss)
        attack_paths.append(
            {
                "step": f"Potential entry point: TCP/{finding.get('port')} ({service})",
                "target_host": finding.get("hostname", finding.get("ip")),
                "vector": finding.get("vulnerability"),
                "mitre_technique": finding.get("mitre_attack", "T1190"),
                "risk_impact": "Hypothesised attack path — validate segmentation and credentials before treating as an exploitable chain.",
                "evidence_confidence": finding.get("confidence", "Potential"),
            }
        )

    # Use both overall risk and concentration of risk rather than making a
    # large scan automatically appear critical merely because it has many rows.
    average = sum(per_finding_scores) / len(per_finding_scores)
    concentration = max(per_finding_scores)
    density_adjustment = min(10.0, max(0, len(vulnerabilities) - 3) * 2.0)
    final_score = round(min(100.0, average * 0.65 + concentration * 0.35 + density_adjustment), 1)
    criticality = max((asset.get("criticality", "Low") for asset in assets), key=lambda value: CRITICALITY_SCORE.get(value, 0), default="Low")
    remote_admin = any(finding.get("service") in {"microsoft-ds", "rdp"} for finding in vulnerabilities)
    cleartext = any(finding.get("service") in {"telnet", "ftp", "http"} for finding in vulnerabilities)
    estimated_ransomware = 80.0 if remote_admin else 45.0 if cleartext else 15.0

    return {
        "risk_score": final_score,
        "risk_level": _risk_level(final_score),
        "explanation": (
            f"Explainable weighted risk model evaluated {len(vulnerabilities)} evidence-supported finding(s) across "
            f"{len(assets)} asset(s). Inputs are CVSS, CVE-specific EPSS when available, business criticality, "
            f"network service exposure, and evidence confidence."
        ),
        "zero_trust_readiness_score": round(max(10.0, 100.0 - final_score * 0.75), 1),
        "ransomware_risk_index": estimated_ransomware,
        "cis_controls_coverage": round(max(25.0, 95.0 - len(vulnerabilities) * 8.5), 1),
        "derived_metric_notice": "Zero Trust, ransomware and CIS values are screening estimates, not formal certifications.",
        "attack_paths": attack_paths,
        "analysis": {
            "vulnerability_count": len(vulnerabilities),
            "business_criticality": criticality,
            "exploit_analysis": f"Maximum CVE-specific local EPSS: {max_epss * 100:.0f}%",
            "network_exposure": any(finding.get("service") in EXPOSED_SERVICES for finding in vulnerabilities),
            "internet_exposure_assessed": False,
            "epss_threat_index": round(max_epss, 2),
            "confidence_score": round(sum(confidence_values) / len(confidence_values), 1),
            "model": "Explainable weighted risk model",
            "per_finding_scores": [round(score, 1) for score in per_finding_scores],
        },
    }
